#!/bin/bash
SP="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SP
+x ./div.py ./divnim ./div.php ./div.lua ./div.js ./div.rb ./div.tcl ./credit.pl ./div.exs ./title
./div.py
./title
./divnim

./div.php

./div.lua

./div.js

./div.rb

./div.exs

java Div

./div.tcl
./credit.pl
erl -noshell -s divi start -s init stop